# Site settings
title: Daan
email: studio.a.hundred@gmail.com
description: "안녕하세요. 디자이너 문홍규 입니다."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://se-daan.github.io" # the base hostname & protocol for your site
ga: UA-145066389-1

# Build settings
markdown: kramdown

# Permalinks
permalink: none

# Sass
sass:
  sass_dir: _sass
  style: :compressed

# Custom collection
collections:
  work:
    output: true

# Plugin
plugins:
- jekyll-autoprefixer
